# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &development
  secret_key_base: a0983231f564b5dff0b4f87a72e80b30c2d7d9d7a06a9609b5150d52ce3406628f4eac13a4016b67c1e747634807d8f3afdbeb07bb7e598c613aa14fbfb4656d
  stripe_secret_key: sk_test_aSCqdxHulQO5SBnjbTfertov
  stripe_publishable_key: pk_test_1LYkk7fCrA1bWDbXRUx1zWBx
  token_audience: carko-1475431423846
  token_cert: "-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIV35jaRPxgH8wDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTcw\nNDE2MDA0NTI2WhcNMTcwNDE5MDExNTI2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBALbGayLey2DkPgIqUzVR6tehi2etd+PpbSm9CDlJnsln+5oY\nD8NA+Yz8Y4t3COuKt6lUZTauW54HXlv6GtmMJ9YdFJwY0CzgPgP5UMYSiRoBDKd9\n+7wet6OHicVWuOb4JkqrTWJzRIjafYBUNzUWi4MYPEFpV8ue7J74B4XSJmPCBpBF\nhaK7RgxqYeEqn2k0vSCNXryzGEIv/EkVShUWrYZStePHPPq2OoLHSJq4SkvenT+g\nxO2sAoD9SSXbjhSkQ88ukRddeXyj8ertWAqveRCmMXdVk5eR2WbZN4RPrPJYOyjO\nUPs47p9EJcwHDiZ2KmfizIn6pnpXHrLdiHBFrb8CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBAIjmFX6XQu7zB250yin6kVGdknpyMCESvF3+etvQvQ9s\n5ocvhDRi/Tgw81+Dk3s3SArYNHluI/XdnUTr2JKyUrEG7EW1wil7Xmb5iHrNaI4K\nXmqhIw7aUXVYV2ALpqCU4nMKrWPJUrfQN/f0tUY0HEIBZsJH5qZPUAdghJ1g8ysT\nb8COI1r6jheAQqEVoR0aOT6P/PUyzNFcizd70sp8LUtzjhutOeqZr3Y6D7ERmSUe\nykoTRZBn2a3Q3eK62E1+N569mixLLjWHEsqk5pEw3u7arNXO50xCO753PnrGCJYa\nBMAJ1L2AkVX8lIKjPG1fNy6cESqsTy88XdZFU0l2KD0=\n-----END CERTIFICATE-----\n"
  apns_url: https://api.development.push.apple.com:443
  apns_connection_pool_size: 1
  apns_cert: |
    -----BEGIN CERTIFICATE-----
    MIIFfjCCBGagAwIBAgIIQ2OqiDX2zNMwDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNV
    BAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js
    ZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3
    aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw
    HhcNMTcwNjA5MjM0MTU1WhcNMTgwNjA5MjM0MTU1WjB+MR0wGwYKCZImiZPyLGQB
    AQwNY29tLnFoNGwuQXB5YTE7MDkGA1UEAwwyQXBwbGUgRGV2ZWxvcG1lbnQgSU9T
    IFB1c2ggU2VydmljZXM6IGNvbS5xaDRsLkFweWExEzARBgNVBAsMCk5TMkEyWkxM
    WDMxCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    w5u7i6ArU/GIpfXTNnAz1xvAawTP8NcwzIziN/DPyc1fNoqBszMEk9LHwjck/X6V
    S2aHqD4AaZ0GOgm2FHlN7mPcLtGo459oX0WE8ixjpnR8ZSkdzxCSpYOUnrlqIKNn
    h0n2djOyC3YvJ+NA7lLoJkqjSfIrUE2UF0qLO0fmOFX5rcMUb4z8oxK5ibpXaqkd
    z29pNSKZ15Z7XcwtTXI55OwtavT61PMyOcFqd0P00E5EOntpz6rIY5B7cQ+6EoHu
    ViRs/aTbZUedE9DLmsQjy3AIxfk3kbE78Onh7Pwzlv/rUVeCpBCdK/Nh9eqym2OE
    /WfnH8pATWbKIXQVSzdD3wIDAQABo4IB5TCCAeEwHQYDVR0OBBYEFIG4QuwRPK24
    DRuNsP/MCbblvdUuMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou6
    9kdZxVJUo7cwggEPBgNVHSAEggEGMIIBAjCB/wYJKoZIhvdjZAUBMIHxMIHDBggr
    BgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55
    IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxl
    IHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNh
    dGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMu
    MCkGCCsGAQUFBwIBFh1odHRwOi8vd3d3LmFwcGxlLmNvbS9hcHBsZWNhLzBNBgNV
    HR8ERjBEMEKgQKA+hjxodHRwOi8vZGV2ZWxvcGVyLmFwcGxlLmNvbS9jZXJ0aWZp
    Y2F0aW9uYXV0aG9yaXR5L3d3ZHJjYS5jcmwwCwYDVR0PBAQDAgeAMBMGA1UdJQQM
    MAoGCCsGAQUFBwMCMBAGCiqGSIb3Y2QGAwEEAgUAMA0GCSqGSIb3DQEBBQUAA4IB
    AQCCQ7CS8t2Bm/I6oW7/rJdi5yP8G+jP5B1BwlKmoJI5NgFGwLW7qg5Qf95wnGnS
    wreTyJ8SwkJnUmegxaawViKLiTQaGrrDCdzcoqIuO68UpkTi3qVM1hjJcH7Lnmp1
    OxwxKCThdtLIf5LfLFs5K9+Q7S9YYYIGRlv2RHU9/Ra0XuqNFGKRTC1B89U5vatw
    VMv/LhM+X8qdsPLIFjVksnCVrvUFBzVAURKJrrtVGMWLQWfbK8qPI25BIV5kh5/X
    +Bc9WjBcYyA/cMWn/mhm07qJwnu8lbEMp1R4434Y4OlPkz+B0/a+dS5jMci+Ec+5
    IlQj2RH9AtMli9Rhg/uloOyD
    -----END CERTIFICATE-----
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAw5u7i6ArU/GIpfXTNnAz1xvAawTP8NcwzIziN/DPyc1fNoqB
    szMEk9LHwjck/X6VS2aHqD4AaZ0GOgm2FHlN7mPcLtGo459oX0WE8ixjpnR8ZSkd
    zxCSpYOUnrlqIKNnh0n2djOyC3YvJ+NA7lLoJkqjSfIrUE2UF0qLO0fmOFX5rcMU
    b4z8oxK5ibpXaqkdz29pNSKZ15Z7XcwtTXI55OwtavT61PMyOcFqd0P00E5EOntp
    z6rIY5B7cQ+6EoHuViRs/aTbZUedE9DLmsQjy3AIxfk3kbE78Onh7Pwzlv/rUVeC
    pBCdK/Nh9eqym2OE/WfnH8pATWbKIXQVSzdD3wIDAQABAoIBAEawjQJUi9P2Qa/Y
    OtA9lD50pQEH6C3dVqFVeJtGx5DiSzpmq6CbG1hgoBgr3Y5OpJ1vHC9M2NFSEeH/
    iHG1tNgl9nhlBGfeP9XORdFPAWQyTJIyXbdrAdQWzSrfTt8krlFSBWOKIxnJSBle
    IyT9iS/tYT1j6wtGPfJ82fw+a5CHv3MzOV6k7Qv112s5IBG5KpFIHRNW9JMUIRVy
    T32C29rlMhombC+Qylf15t1OeyU8/vTnUtSFV0MnFX45orKYXeauag0uRaGaQlXK
    ZnbX5NXikgOPDFYiqyEdxnjAg0mijUNq44tjcv8hSKLfTjqqbnvxSYv9obvuUZT3
    dY56weECgYEA7rsiy3Xvw+a4YkHP1Hx3X00WPxEri+sd5A726HgE5VRXJdQAxVjh
    zHf1RXm9L3yvKLH44l0yz1/nR54wENfT7eN/pZE48NV+UXGZtVRAt/xFmKwvDTbH
    Vva1Pf3DclgHrF+eulGO6qvQiqBw4h7Zw2BhDoU6G/c/gw7qpVwbjm0CgYEA0cIL
    ElkN5dfGyIwuAqlvkYRwGPBBKWZYdwlyKXefeCEFpgNiTjzCjsehsxJ7ONAYpESa
    1J/+hnoaILMEqToKkIUwQA5hP/Q5fk4+N9s4Ma5QGPUSJ4gxQ2gwJfX6PDqgUN2o
    n5zXD/3zHHdqq3+ZyM7hWC3gdKbq52Yk19otu/sCgYBX9NbDA7bNBKqWeQzritgo
    Yqx5nAfhS0T+C41o5R9YpxRcuZl3HGJFBUV2zX2oi1W1tqyuKgxYX0tFFcE702kf
    0pvrEnBaOy6JL0OkjWAy6V1y/K1xPud+4PKx3lcuP8TD+47tsrLnP1pcWPR+O0Oc
    OlxID0nzl8rsrIhDWIZGmQKBgFXF4l8jWWKGZLv3To06GexIWspn3E2Ak2ZBz5QT
    XXtzDWtAcP+LKwfVrFKcmRS3S4xInYOa1SrKXUrHyX0lxdIpFHztJGlRhf0XI6wV
    kZoHLKu38y+FKpfkz+OF/UiJtKq8qUpziSH592LJli4A5LLPnig/wkwRQXdUNnap
    ug/nAoGAONtyxMATcOPG9oEnIRv/eJsOLWDc3QC0Thp1/BSJpT+zEzyq2PRwcbqm
    Fb3+RX7baxr/qjLHwy8EXQzjtvy4wXQ6b53KNnjTkgAVSuSzcuT9oIc7Dgrr29j3
    WySSmmqvojNQk4tnt+P8/aeLPzpVXrsO67Qr+kFIluMPQEgdpkU=
    -----END RSA PRIVATE KEY-----


test:
  <<: *development

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  token_audience: <%= ENV["TOKEN_AUDIENCE"] %>
  token_cert: <%= ENV["TOKEN_CERT"] %>
  apns_url: https://api.push.apple.com:443
  apns_connection_pool_size: 10
  apns_cert: <%= ENV["APNS_CERT"] %>
