# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0983231f564b5dff0b4f87a72e80b30c2d7d9d7a06a9609b5150d52ce3406628f4eac13a4016b67c1e747634807d8f3afdbeb07bb7e598c613aa14fbfb4656d
  stripe_secret_key: sk_test_aSCqdxHulQO5SBnjbTfertov
  stripe_publishable_key: pk_test_1LYkk7fCrA1bWDbXRUx1zWBx
  token_audience: carko-1475431423846
  token_cert: "-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIV35jaRPxgH8wDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTcw\nNDE2MDA0NTI2WhcNMTcwNDE5MDExNTI2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBALbGayLey2DkPgIqUzVR6tehi2etd+PpbSm9CDlJnsln+5oY\nD8NA+Yz8Y4t3COuKt6lUZTauW54HXlv6GtmMJ9YdFJwY0CzgPgP5UMYSiRoBDKd9\n+7wet6OHicVWuOb4JkqrTWJzRIjafYBUNzUWi4MYPEFpV8ue7J74B4XSJmPCBpBF\nhaK7RgxqYeEqn2k0vSCNXryzGEIv/EkVShUWrYZStePHPPq2OoLHSJq4SkvenT+g\nxO2sAoD9SSXbjhSkQ88ukRddeXyj8ertWAqveRCmMXdVk5eR2WbZN4RPrPJYOyjO\nUPs47p9EJcwHDiZ2KmfizIn6pnpXHrLdiHBFrb8CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBAIjmFX6XQu7zB250yin6kVGdknpyMCESvF3+etvQvQ9s\n5ocvhDRi/Tgw81+Dk3s3SArYNHluI/XdnUTr2JKyUrEG7EW1wil7Xmb5iHrNaI4K\nXmqhIw7aUXVYV2ALpqCU4nMKrWPJUrfQN/f0tUY0HEIBZsJH5qZPUAdghJ1g8ysT\nb8COI1r6jheAQqEVoR0aOT6P/PUyzNFcizd70sp8LUtzjhutOeqZr3Y6D7ERmSUe\nykoTRZBn2a3Q3eK62E1+N569mixLLjWHEsqk5pEw3u7arNXO50xCO753PnrGCJYa\nBMAJ1L2AkVX8lIKjPG1fNy6cESqsTy88XdZFU0l2KD0=\n-----END CERTIFICATE-----\n"

test:
  secret_key_base: 88eb183c904403b46321592df50502f749a941feea413443a39181c19166fa99e82111d23505225557b89d5b3a0dd8e4aa9eff549d3ce25aa5cc6e465eb7c986
  stripe_secret_key: sk_test_aSCqdxHulQO5SBnjbTfertov
  stripe_publishable_key: pk_test_1LYkk7fCrA1bWDbXRUx1zWBx
  token_audience: carko-1475431423846
  token_cert: "-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIV35jaRPxgH8wDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTcw\nNDE2MDA0NTI2WhcNMTcwNDE5MDExNTI2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBALbGayLey2DkPgIqUzVR6tehi2etd+PpbSm9CDlJnsln+5oY\nD8NA+Yz8Y4t3COuKt6lUZTauW54HXlv6GtmMJ9YdFJwY0CzgPgP5UMYSiRoBDKd9\n+7wet6OHicVWuOb4JkqrTWJzRIjafYBUNzUWi4MYPEFpV8ue7J74B4XSJmPCBpBF\nhaK7RgxqYeEqn2k0vSCNXryzGEIv/EkVShUWrYZStePHPPq2OoLHSJq4SkvenT+g\nxO2sAoD9SSXbjhSkQ88ukRddeXyj8ertWAqveRCmMXdVk5eR2WbZN4RPrPJYOyjO\nUPs47p9EJcwHDiZ2KmfizIn6pnpXHrLdiHBFrb8CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBAIjmFX6XQu7zB250yin6kVGdknpyMCESvF3+etvQvQ9s\n5ocvhDRi/Tgw81+Dk3s3SArYNHluI/XdnUTr2JKyUrEG7EW1wil7Xmb5iHrNaI4K\nXmqhIw7aUXVYV2ALpqCU4nMKrWPJUrfQN/f0tUY0HEIBZsJH5qZPUAdghJ1g8ysT\nb8COI1r6jheAQqEVoR0aOT6P/PUyzNFcizd70sp8LUtzjhutOeqZr3Y6D7ERmSUe\nykoTRZBn2a3Q3eK62E1+N569mixLLjWHEsqk5pEw3u7arNXO50xCO753PnrGCJYa\nBMAJ1L2AkVX8lIKjPG1fNy6cESqsTy88XdZFU0l2KD0=\n-----END CERTIFICATE-----\n"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  token_audience: <%= ENV["TOKEN_AUDIENCE"] %>
  token_cert: <%= ENV["TOKEN_CERT"] %>
